### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Emmiez** [zhycorp/disc-11#127]
Recently this started not too long ago idk what it mean may anyone help me?

/app/dist/utils/Logger.js:14
5:53 PM
        .replace(/<hour>/g, data.find(({ type }) => type === "hour").value)
5:53 PM
                                                                    ^
5:53 PM
5:53 PM
TypeError: Cannot read property 'value' of undefined
5:53 PM
    at formatDateForLogFile (/app/dist/utils/Logger.js:14:69)
5:53 PM
    at Object.createLogger (/app/dist/utils/Logger.js:40:92)
5:53 PM
    at Object.<anonymous> (/app/dist/main.js:8:22)
5:53 PM
    at Module._compile (internal/modules/cjs/loader.js:759:30)
5:53 PM
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
5:53 PM
    at Module.load (internal/modules/cjs/loader.js:628:32)
5:53 PM
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
5:53 PM
    at Module.require (internal/modules/cjs/loader.js:666:19)
5:53 PM
    at require (internal/modules/cjs/helpers.js:16:16)
5:53 PM
Jump Toat start (/app/start.js:30:5)

**Comment by mozartrafi** [comment]
Hey @Emmiez 👋 

Sorry about that, but you can try remixing your project until you get a supported version of the node.
This can happen as in [a message](https://discord.com/channels/332877090003091456/615705226372055040/787356963611738162) that I have announced on our [Discord server](https://discord.gg/zhycorp)

**Comment by mozartrafi** [comment]
Let me know if you have another questions

**Comment by mozartrafi** [comment]
Y
