### ISSUE TITLE
[ERROR] Can't Find Module './dist/main.js'

### ISSUE THREAD

**Issue by recovdot** [zhycorp/disc-11#214]
Error: Cannot find module './dist/main.js'
Require stack:
- /home/idabagustomoeisozaki/disc-11/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at start (/home/idabagustomoeisozaki/disc-11/start.js:30:5)
    at Object.<anonymous> (/home/idabagustomoeisozaki/disc-11/start.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/idabagustomoeisozaki/disc-11/start.js' ]
}

**Comment by 21Z** [comment]
Have you run `npm run build` ?
![unknown](https://user-images.githubusercontent.com/69188068/111032601-6bf87200-8426-11eb-81ea-34697fef7aef.png)

**Comment by mzrtamp** [comment]
New releases should fix this issue, try to re-fork this project, and import it again.
Or you can try a solution as stated by @21Z

**Comment by MoustacheOff** [comment]
Same problem, I tried everything.
```
(base) ➜  disc-11 git:(main) ✗ node start.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist/main.js'
Require stack:
- /Users/g.corral/Desktop/disc-11/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
    at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
}
(base) ➜  disc-11 git:(main) ✗ npm start.js
Unknown command: "start.js"

Did you mean one of these?
    npm stars # View packages marked as favorites
    npm start # Start a package

To see a list of supported npm commands, run:
  npm help
(base) ➜  disc-11 git:(main) ✗ node start.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist/main.js'
Require stack:
- /Users/g.corral/Desktop/disc-11'/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
    at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
}
(base) ➜  disc-11 git:(main) ✗ npm start

> disc-11@1.0.0 start
> node start.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist/main.js'
Require stack:
- /Users/g.corral/Desktop/disc-11start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
    at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
}
(base) ➜  disc-11 git:(main) ✗ npm run build

> chibivibin@1.0.0 build
> npm run lint && npm run compile


> chibivibin@1.0.0 lint
> eslint . --ignore-path .gitignore --ext .ts

sh: eslint: command not found
(base) ➜  disc-11 git:(main) ✗ npm start

> chibivibin@1.0.0 start
> node start.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist/main.js'
Require stack:
- /Users/g.corral/Desktop/disc-11/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
    at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
}
(base) ➜  disc-11 git:(main) ✗ npm install

added 149 packages, and audited 281 packages in 20s

30 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
(base) ➜  disc-11 git:(main) ✗ npm start

> chibivibin@1.0.0 start
> node start.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist/main.js'
Require stack:
- /Users/g.corral/Desktop/disc-11/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
    at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
}
```

**Comment by mzrtamp** [comment]
> Same problem, I tried everything.
> 
> ```
> (base) ➜  disc-11 git:(main) ✗ node start.js
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module './dist/main.js'
> Require stack:
> - /Users/g.corral/Desktop/disc-11/start.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
>     at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
> }
> (base) ➜  disc-11 git:(main) ✗ npm start.js
> Unknown command: "start.js"
> 
> Did you mean one of these?
>     npm stars # View packages marked as favorites
>     npm start # Start a package
> 
> To see a list of supported npm commands, run:
>   npm help
> (base) ➜  disc-11 git:(main) ✗ node start.js
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module './dist/main.js'
> Require stack:
> - /Users/g.corral/Desktop/disc-11'/start.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
>     at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
> }
> (base) ➜  disc-11 git:(main) ✗ npm start
> 
> > disc-11@1.0.0 start
> > node start.js
> 
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module './dist/main.js'
> Require stack:
> - /Users/g.corral/Desktop/disc-11start.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
>     at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
> }
> (base) ➜  disc-11 git:(main) ✗ npm run build
> 
> > chibivibin@1.0.0 build
> > npm run lint && npm run compile
> 
> 
> > chibivibin@1.0.0 lint
> > eslint . --ignore-path .gitignore --ext .ts
> 
> sh: eslint: command not found
> (base) ➜  disc-11 git:(main) ✗ npm start
> 
> > chibivibin@1.0.0 start
> > node start.js
> 
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module './dist/main.js'
> Require stack:
> - /Users/g.corral/Desktop/disc-11/start.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
>     at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
> }
> (base) ➜  disc-11 git:(main) ✗ npm install
> 
> added 149 packages, and audited 281 packages in 20s
> 
> 30 packages are looking for funding
>   run `npm fund` for details
> 
> 3 moderate severity vulnerabilities
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> (base) ➜  disc-11 git:(main) ✗ npm start
> 
> > chibivibin@1.0.0 start
> > node start.js
> 
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module './dist/main.js'
> Require stack:
> - /Users/g.corral/Desktop/disc-11/start.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/Users/g.corral/Desktop/disc-11/start.js:30:5)
>     at Object.<anonymous> (/Users/g.corral/Desktop/disc-11/start.js:21:1)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ "/Users/g.corral/Desktop/disc-11/start.js" ]
> }
> ```

`$ npm run build` first
